---
title: "Group Activity"
format:
  html:
    toc: true
---

Group A will be analyzing the yogurt dataset and Group B will be analyzing the menstruation dataset.


<!-- :::{.callout-Group_A}

<b>Study Description</b>  

::: -->

### Projects

<!-- :::{.callout-note title="Research Project A - Does yogurt consumption change the vaginal microbiome?" appearance="simple"}
\
**Aim**\
To investigate whether the consumption of yogurt influences microbiome composition after antibiotics treatment.\
\
**Study Description** \
This is a randomized controlled trial to study whether yogurt consumption has an effect on the microbiome post antibiotic treatment. Absolute abundance of bacteria (in gene copies / mL) was measured by 3 qPCR assays (for total, L. crispatus, L. iners). Cytokine levels (in ug/mL of vaginal fluid) were also measured by Luminex. We also looked at the number and type of immune cells in the vagina using Flow Cytometry. Data was collected at two timepoints, pre and post antibiotic treatment. (add 16s)
\
 
::: -->

:::{.block}
::::{.block-header} 
Research Project A - Does yogurt consumption change the vaginal microbiome?
::::
::::{.block-container id="group_a"}
**Aim**\
To investigate whether the consumption of yogurt influences microbiome composition after antibiotics treatment.\
\
**Study Description** \
This is a randomized controlled trial to study whether yogurt consumption has an effect on the microbiome post antibiotic treatment. 16S rRNA sequencing was done to charaterize patient microbiome composition. Absolute abundance of bacteria (in gene copies / mL) was measured by 3 qPCR assays (for total, L. crispatus, L. iners). Cytokine levels (in ug/mL of vaginal fluid) were also measured by Luminex. We also looked at the number and type of immune cells in the vagina using Flow Cytometry. Data was collected at two timepoints, pre and post antibiotic treatment.
\
::::
:::
<script> 
  // Add click event listener to the block header
  document.getElementById("group_a").addEventListener("click", function() {
    window.location.href = "group_a.html";
  });
</script>




:::{.block}
::::{.block-header}
Research Project B - Does birth control change inflammation during menstruation?
::::
::::{.block-container id="group_b"}
**Aim**\
To investigate whether taking birth control is associated with vaginal inflammation throughout the menstrual cycle.\
\
**Study Description** \
This is an observational study to evaluate the relationship between birth control and vaginal inflammation In response to menstruation. 16S rRNA sequencing was done to charaterize patient microbiome composition. Absolute abundance of bacteria was measured by 3 qPCR assays (for total Bacteria, L. crispatus, L. iners). Cytokine levels (in ug/mL of vaginal fluid) were also measured by Luminex. We also looked at the number and type of immune cells in the vagina using Flow Cytometry. Data was collected at four timepoints; before, at the start, the end, and after menstruation.
\
::::
:::
<script> 
  // Add click event listener to the block header
  document.getElementById("group_b").addEventListener("click", function() {
    window.location.href = "group_b.html";
  });
</script>


<!-- :::{.goals}
::::{.goals-header}
Learning Goals
::::
::::{.goals-container}
* Know how to make your own callouts.
* Be able to mess with some SCSS/CSS styling.
::::
::: -->


<!-- {{< group_projects.qmd >}} -->



### Schedule
**Wednesday (4/24)**

+----------------+-----------------------------------------------------------------------------------+
| Time           | Task                                                                              |
+================+===================================================================================+
| 9:00-9:30am    |- Read project description and aims for your project                               |
|                |- Locate project files on your instance                                            |
|                |- Create a new .qmd file                                                           |
+----------------+-----------------------------------------------------------------------------------+
| 9:30 - 10:30am |- **Explore the data!**                                                            |
|                |- Merge in metadata, qPCR, and Luminex data                                        |
|                |- Create a phyloseq object                                                         |
+----------------+-----------------------------------------------------------------------------------+
|10:30 - 11:00am | **Break**                                                                         |
+----------------+-----------------------------------------------------------------------------------+
|11:00- 12:00pm  |- Phyloseq cleaning                                                                |
|                |- Visualizing microbiome composition                                               |
|                |- Diversity and Ordination                                                         |
+----------------+-----------------------------------------------------------------------------------+


**Thursday (4/25)**

+----------------+-------------------------------------------------------------------------------------+
| Time           | Task                                                                                |
+================+=====================================================================================+
| 1:30 - 2:00pm  |- Diversity and Ordination                                                           |
+----------------+-------------------------------------------------------------------------------------+
| 2:00 - 3:00pm  |- Differential abundance                                                             |
+----------------+-------------------------------------------------------------------------------------+
|3:00 - 3:30pm   | **Break**                                                                           |
+----------------+-------------------------------------------------------------------------------------+
|3:30 - 5:00pm   |- Integrating shotgun metagenomics                                                   |
+----------------+-------------------------------------------------------------------------------------+

### Example workflows
[Johnathan's test demo](johnathan_demo_final.qmd)

