---
title: "Group activities"
---

```{r}

library(tidyverse)
library(tableone)
# library(kableone)
library(flextable)
library(pander)
library(gtsummary)

```

## Group 1 table 1

```{r}

g1_00 <- read_csv("group1_dataset/00_sample_ids_yogurt.csv")
g1_01 <- 
  read_csv("group1_dataset/01_participant_metadata_yogurt.csv")


```

```{r}

g1_t1 <- 
  tableone::CreateTableOne(
  data = g1_01,
  vars = 
    c("days_since_last_sex", "birth_control", "age", "education"),
  strata = c("arm")
  )

g1_t1


```

```{r}

print(g1_t1, nonnormal = c("age", "days_since_last_sex"))

```

```{r}


g1_gt1 <-  
  g1_01 %>%
  select(-pid, -sex) |> 
  tbl_summary(by = arm) |> 
  add_p()

g1_gt1
```

```{r}

ggplot(g1_01, aes(x = birth_control, fill = arm)) +
  geom_bar() 

```

```{r}




table(g1_01$birth_control, g1_01$arm) |> 
chisq.test()

table(g1_01$birth_control, g1_01$arm) |> 
chisq.test(correct = FALSE)


table(g1_01$birth_control, g1_01$arm) |> 
chisq.test(simulate.p.value = FALSE)


table(g1_01$birth_control, g1_01$arm) |> 
chisq.test(simulate.p.value = FALSE, rescale.p = TRUE)


table(g1_01$birth_control, g1_01$arm) |> 
chisq.test(simulate.p.value = TRUE)



table(g1_01$birth_control, g1_01$arm) |> 
chisq.test(simulate.p.value = TRUE, rescale.p = TRUE, B = 500)


table(g1_01$birth_control, g1_01$arm) |> 
fisher.test()

```

## Group 2 table 1

```{r}

g2_00 <- read_csv("group2_dataset/00_sample_ids_period.csv")
g2_01 <- 
  read_csv("group2_dataset/01_participant_metadata_period.csv")


```

```{r}

g2_t1 <- 
  tableone::CreateTableOne(
  data = g2_01,
  vars = 
    c("pcos", "period_product", "age"),
  strata = c("arm")
  )

g2_t1

```

```{r}

g2_gt1 <-  
  g2_01 %>%
  select(-pid, -sex) |> 
  tbl_summary(by = arm) |> 
  add_p()

g2_gt1
```

```{r}


wilcox.test(age ~ arm, g2_01)

t.test(age ~ arm, g2_01)


```

```{r}

ggplot(g2_01, aes(x = age, fill = arm)) +
  geom_histogram(binwidth = 1) +
  facet_grid(arm ~ .)

```
